version: "3.9"

services:
  # Rust and Cargo in a Docker container.
  cargo:
    build:
      network: host
      context: ./docker/rust
    image: babycat/rust
    init: true
    network_mode: host
  # A big Docker container that contains many versions of
  # Python and various debugging tools.
  main:
    build:
      network: host
      context: ./docker/main
    image: babycat/main
    init: true
    network_mode: host
    working_dir: /host
    volumes:
      - type: bind
        source: "."
        target: /host
  # A container for the purpose of building manylinux wheels.
  pip:
    build:
      network: host
      context: ./docker/pip
    image: babycat/pip
    init: true
    network_mode: host
    entrypoint: pip
    working_dir: /io
    volumes:
      - type: bind
        source: "."
        target: /io
