[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

# These rustflags are necessary for building Babycat's Python bindings
# on MacOS.
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

# Statically link to the MSVC C Runtime (CRT) on the Windows MSVC
# target. This reduces the need for Babycat users to install
# the MSVC vc_redist.exe binary.
# Further reading:
# - https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md
# - https://georgik.rocks/how-to-statically-link-rust-application-for-windows/
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
