[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

# These rustflags are necessary for linking babycat-binding-python to
# Python development on Mac OS X.
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
