# This Action builds the babycat command line program on macOS.
name: build-binary-macos

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /Users/runner/.cargo
  RUSTUP_HOME: /Users/runner/.rustup
  MACOSX_DEPLOYMENT_TARGET: 10.7

jobs:
  build-binary-macos:
    runs-on: macos-10.15

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true

    steps:
    - uses: actions/checkout@v2

    - name: Vendor Rust code
      run: make vendor

    - name: Build babycat command line program
      run: make build-binary
