# This Action builds the babycat command line program on Linux.
name: build-binary-linux

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /usr/share/rust/.cargo
  RUSTUP_HOME: /usr/share/rust/.rustup

jobs:
  build-binary-linux:
    runs-on: ubuntu-20.04

    steps:

    - name: Install ALSA development headers
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends libasound2-dev

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true

    - uses: actions/checkout@v2

    - name: Cache vendored Rust dependencies
      id: cache-vendored-rust-dependencies
      uses: actions/cache@v2
      with:
        path: ./vendor
        key: build-binary-linux-${{ hashFiles('./Cargo.toml') }}

    - name: Vendor Rust code (if it is not cached)
      run: make vendor
      if: steps.cache-vendored-rust-dependencies.outputs.cache-hit != 'true'

    - name: Build babycat command line program
      run: make build-binary
