# This Action builds the Babycat command line program.
name: build-binary

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "10.7"

jobs:
  build-binary:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-20.04"
          - "macos-10.15"
          - "windows-2019"
    steps:

    - name: Install ALSA development headers (Ubuntu only)
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends libasound2-dev

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.56.0"
          override: true

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Build `babycat` command line program
      run: make build-binary
