# Deploy Sphinx docs to production
name: docs-sphinx-prod

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always

jobs:
  docs-sphinx-prod:
    runs-on: ubuntu-20.04

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.56.0"
          override: true
          target: wasm32-unknown-unknown

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Install wasm-pack
      run: |
        wget https://github.com/rustwasm/wasm-pack/releases/download/v0.10.2/wasm-pack-v0.10.2-x86_64-unknown-linux-musl.tar.gz
        tar xvf wasm-pack-v0.10.2-x86_64-unknown-linux-musl.tar.gz
        cp wasm-pack-v0.10.2-x86_64-unknown-linux-musl/wasm-pack .
        rm -rfv wasm-pack-v0.10.2-x86_64-unknown-linux-muslwasm-pack-v0.10.2-x86_64-unknown-linux-musl.tar.gz

    - name: Deploy Sphinx docs on Netlify
      run: WASM_PACK=$PWD/wasm-pack make deploy-docs-sphinx-netlify-prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
