# This formats and lints babycat's source code.
name: fmt-lint

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-lint:
    runs-on: ubuntu-20.04

    steps:

    - name: Install ALSA development headers
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends libasound2-dev

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.56.0"
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - uses: actions/checkout@v2

    - name: Vendor Rust code
      run: make vendor

    - name: Check code formatting
      run: make fmt-check

    - name: Lint code
      run: make lint
