# This formats and lints babycat's source code.
name: fmt-lint

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-lint:
    runs-on: ubuntu-20.04

    steps:

    # We need the ALSA headers for building/linting the Babycat CLI app.
    # We need yasm for buildling/linting FFmpeg.
    - name: Install ALSA development headers and yasm
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends libasound2-dev yasm

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.56.0"
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

    - name: Install Python
      uses: actions/setup-python@v2
      id: setup-python
      with:
        python-version: "3.8"

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Cache the Python virtualenv
      uses: actions/cache@v2
      with:
        path: venv
        key: fmt-lint-${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-requirements-${{ hashFiles('**/requirements*.txt') }}

    - name: Check code formatting
      run: make fmt-check

    - name: Lint code
      run: make lint
