name: publish-github-release

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish-github-release:
    runs-on: ubuntu-20.04

    steps:

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v3

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
