name: publish-wasm

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /usr/share/rust/.cargo
  RUSTUP_HOME: /usr/share/rust/.rustup

jobs:
  publish-wasm:
    runs-on: ubuntu-20.04

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true
          target: wasm32-unknown-unknown

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - uses: actions/checkout@v2

    - name: Get the version from the Git tag name
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Set the version in our Cargo.toml
      run: ./.version-bump.py ${{ steps.get_version.outputs.VERSION }}

    - name: Install wasm-pack
      run: cargo install wasm-pack --version=^0.10.1

    - name: Vendor Rust code
      run: make vendor

    - name: Build the WebAssembly bundle
      run: make build-wasm-bundler

    - name: Publish to NPM
      run: npm publish
      working-directory: ./target/frontend-wasm/release/bundler
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
