name: publish-python

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: 10.7

jobs:
  publish-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-20.04
            cargo_home: /usr/share/rust/.cargo
            rustup_home: /usr/share/rust/.rustup
          - os: macos-10.15
            cargo_home: /Users/runner/.cargo
            rustup_home: /Users/runner/.rustup
          - os: windows-2019
            cargo_home: C:\Rust\.cargo
            rustup_home: C:\Rust\.rustup

    steps:

    - uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Set the version in our Cargo.toml
      run: ./.version-bump.py ${{ steps.get_version.outputs.VERSION }}

    - name: Install Python build tools
      run: python3 -m pip install --upgrade pip wheel twine

    - name: Vendor Rust code
      run: make vendor

    - name: Build Windows and MacOS Python wheels
      if: matrix.os != 'ubuntu-20.04'
      run: make build-python

    - name: Build the manylinux Python wheel
      if: matrix.os == 'ubuntu-20.04'
      run: make build-python-manylinux

    - name: Publish to PyPI
      run: twine upload --non-interactive target/python/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
