name: publish-rust

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "10.7"

jobs:
  publish-rust:
    runs-on: ubuntu-20.04

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.56.0"
          override: true

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Get the version from our Git tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Set the version in our Cargo.toml
      run: ./.version-bump.py ${{ steps.get_version.outputs.VERSION }}

    - name: Log into crates.io
      run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

    - name: Publish to crates.io
      run: cargo publish --allow-dirty
