name: publish-wasm

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-wasm:
    runs-on: ubuntu-20.04

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.61.0"
          override: true
          target: wasm32-unknown-unknown

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Get the version from the Git tag name
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Set the version in our Cargo.toml
      run: ./.version-bump.py ${{ steps.get_version.outputs.VERSION }}

    - name: Install wasm-pack
      run: |
        wget https://github.com/rustwasm/wasm-pack/releases/download/v0.10.2/wasm-pack-v0.10.2-x86_64-unknown-linux-musl.tar.gz
        tar xvf wasm-pack-v0.10.2-x86_64-unknown-linux-musl.tar.gz
        cp wasm-pack-v0.10.2-x86_64-unknown-linux-musl/wasm-pack .
        rm -rfv wasm-pack-v0.10.2-x86_64-unknown-linux-muslwasm-pack-v0.10.2-x86_64-unknown-linux-musl.tar.gz

    - name: Build the WebAssembly bundle
      run: WASM_PACK=$PWD/wasm-pack make build-wasm-bundler

    - name: Configure NPM authentication
      run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      working-directory: ./target/release/wasm/bundler

    - name: Publish to NPM
      run: npm publish
      working-directory: ./target/release/wasm/bundler
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
