# Runs the tests for Babycat's Rust frontend with FFmpeg enabled.
name: test-rust-ffmpeg

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust-ffmpeg:
    runs-on: "ubuntu-20.04"

    steps:

    # We need yasm for buildling/linting FFmpeg.
    - name: Install yasm for building FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends yasm

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.56.0"
          override: true

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Vendor Rust code
      run: make vendor

    - name: Build FFmpeg and Rust frontend
      run: ENABLE_FFMPEG_BUILD_LINK_STATIC=1 make build-rust

    - name: Run Rust tests
      run: ENABLE_FFMPEG_BUILD_LINK_STATIC=1 make test-rust
