# Run the tests for the Python manylinux wheel with FFmpeg enabled.
name: test-python-ffmpeg-manylinux

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

jobs:
  test-python-ffmpeg-manylinux:
    runs-on: "ubuntu-20.04"

    steps:

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Build the manylinux Python frontend with FFmpeg
      run: make build-python-ffmpeg-manylinux

    - name: Run Python tests
      run: make test-python-ffmpeg-manylinux
