# Runs the tests for Babycat's Python frontend.
name: test-python

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "10.7"

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - "ubuntu-20.04"
          - "macos-10.15"
          - "windows-2019"

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.61.0"
          override: true

    - name: Install Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v3

    - name: Cache the Python virtualenv
      uses: actions/cache@v2
      with:
        path: venv
        key: test-python-${{ matrix.os }}-python-${{ steps.setup-python.outputs.python-version }}-requirements-${{ hashFiles('**/requirements*.txt') }}

    - name: Run Python tests
      run: make test-python
