# Runs the tests for Babycat's Python frontend.
name: test-python

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "10.7"

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - "ubuntu-20.04"
          - "macos-10.15"
          - "windows-2019"

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.56.0"
          override: true

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Vendor Rust code
      run: make vendor

    - name: Build Python frontend
      run: make build-python

    - name: Run Python tests
      run: make test-python
      if: matrix.python-version == '3.8' || matrix.python-version == '3.9' || matrix.python-version == '3.10'
