# This Action runs the unit tests for babycat's Python frontend on Linux.
name: test-python-linux

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /usr/share/rust/.cargo
  RUSTUP_HOME: /usr/share/rust/.rustup

jobs:
  test-python-linux:
    runs-on: ubuntu-20.04

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - uses: actions/checkout@v2

    - name: Cache vendored Rust dependencies
      uses: actions/cache@v2
      with:
        path: ./vendor
        key: test-python-linux-${{ hashFiles('./Cargo.toml') }}

    - name: Vendor Rust code (if it is not cached)
      run: make vendor

    - name: Build Python frontend
      run: make build-python

    - name: Run Python tests
      run: make test-python
