# This Action runs the unit tests for babycat's Rust frontend on Windows.
name: test-rust-windows

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: C:\Rust\.cargo
  RUSTUP_HOME: C:\Rust\.rustup

jobs:
  test-rust-windows:
    runs-on: windows-2019

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true

    - uses: actions/checkout@v2

    - name: Cache vendored Rust dependencies
      uses: actions/cache@v2
      with:
        path: ./vendor
        key: test-rust-windows-${{ hashFiles('./Cargo.lock') }}

    - name: Vendor Rust code (if it is not cached)
      run: make vendor

    - name: Build Rust frontend
      run: make build-rust

    - name: Run Rust tests
      run: make test-rust
