# Runs the tests for Babycat's Rust frontend with FFmpeg enabled.
name: test-ffmpeg-rust

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ffmpeg-rust:
    runs-on: "ubuntu-20.04"

    steps:

    - name: Install yasm for building FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends yasm

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.61.0"
          override: true

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v2

    - name: Build and run Rust tests with FFmpeg
      run: make test-ffmpeg-rust
