# This Action runs the unit tests for babycat's Rust frontend on Linux.
name: test-rust-linux

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /usr/share/rust/.cargo
  RUSTUP_HOME: /usr/share/rust/.rustup

jobs:
  test-rust-linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true

    - name: Vendor Rust code
      run: make vendor

    - name: Run Rust tests
      run: make test-rust
