# This Action runs the unit tests for babycat's Python frontend on macOS.
name: test-python-macos

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /Users/runner/.cargo
  RUSTUP_HOME: /Users/runner/.rustup
  MACOSX_DEPLOYMENT_TARGET: 10.7

jobs:
  test-python-macos:
    runs-on: macos-10.15

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - uses: actions/checkout@v2

    - name: Vendor Rust code
      run: make vendor

    - name: Build Python frontend
      run: make build-python

    - name: Run Python tests
      run: make test-python
