# This Action runs the unit tests for babycat's WebAssembly frontend on Linux.
name: test-wasm-linux

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: /usr/share/rust/.cargo
  RUSTUP_HOME: /usr/share/rust/.rustup

jobs:
  test-wasm-linux:
    runs-on: ubuntu-20.04

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    steps:
    - uses: actions/checkout@v2

    - name: Vendor Rust code
      run: make vendor

    - name: Setup JavaScript requirements
      run: make init-javascript

    - name: Run WebAssembly tests
      run: make build-wasm-nodejs

    - name: Run WebAssembly tests
      run: make test-wasm-nodejs
