# Runs the tests for Babycat's Python frontend.
name: test-c

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "10.7"

jobs:
  test-c:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-20.04"
          - "macos-10.15"

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.61.0"
          override: true

    - name: Check out Babycat code from GitHub
      uses: actions/checkout@v3

    - name: Run C tests
      run: make test-c
