name: test-wasm

defaults:
  run:
    shell: bash

on:
  pull_request:
  push:
    tags-ignore:
      - 'v*' # Don't run these tests twice when cutting a new version.

env:
  CARGO_TERM_COLOR: always

jobs:
  test-wasm:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: "1.53.0"
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Run WebAssembly tests with NodeJS
      run: make test-wasm-nodejs
